---
- name: Delete Pool
  bigip_pool:
      server: "{{ f5_server }}"
      user: "{{ admin_user }}"
      password: "{{ vault_f5_password }}"
      state: "absent"
      name: "{{ pool_name}}"
      partition: "Common"